### ISSUE TITLE
There is no evidence of Core3 being "The worlds most powerful CMS"

### ISSUE THREAD

**Issue by domgoodwin** [Core3Project/Core3-CMS#1]
Core3 CMS is the Worlds Most Powerful CMS

**Comment by ethanduncan** [comment]
Hi Dom, don't worry about it.

**Comment by ethanduncan** [comment]
Also Dom lrn2code

**Comment by zubairfazal** [comment]
Hi Dom, currently this is a work in progress and still has alot of development left. However we have the fatest php theming engine ever built, which is truly amazing

**Comment by zubairfazal** [comment]
> Core3 CMS is the Worlds Most Powerful CMS

I am recoding it using NodeJS
