### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by yerfry** [Core3Project/Core3-CMS#3]
So I got to use the most powerful CMS in the world, but now I need help, you need to pay the hospital bills cause I got cancer from it.

**Comment by zubairfazal** [comment]
Would you like to join the project and assist?

**Comment by yerfry** [comment]
To be honest, this project isn't worth it unless you actually learn a substantional amount of php because as it looks right now it won't be worth much and looks messy. If you do need help then do find me on my facebook account and send me a pm, I'll give you as much assistance as you need.

**Comment by zubairfazal** [comment]
It would be good if I can get some assistance with the core structure on how I should do the MVC. The Project was made to learn PHP, and I understand currently the code may not be great, but with others we can improve and make it usable.
